### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Devir0R** [goolime/sadna192#5]
write all tests for all the Use-cases
- [x] 1.1 System start
- [x] 2.2 guest buyer
- [x] 2.3 login
- [x] 2.5 product search
- [x] 2.6  save product in cart
- [x] 2.7.1 show cart
- [x] 2.7.2 edit cart
- [x] 2.8.1 buy product
- [x] 2.8.2 policy check
- [x] 2.8.3 proceed to checkout
- [x] 2.8.4 immediate buy
- [x] 3.1 log out
- [x] 3.2 open store
- [x] 4.1.1 add product to shop
- [x] 4.1.2 remove product from shop
- [x] 4.1.3 edit product in shop
- [x] 4.3 make someone owner
- [x] 4.4 remove someone from ownership
- [x] 4.5 make someone shop manager
- [x] 4.6 remove someone from management
- [x] 5.1 manager's permission
- [x] 6.2 remove signed user

**Comment by goolime** [comment]
@michallor you can copy the tests base from [here](https://github.com/goolime/sadna192/tree/b26dd413c542f38af0e5aff912147131e8678c0f)
